name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  use-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD repository
        uses: actions/checkout@v4
        with:
          repository: integer-bin/helm-repo
          ref: main
          token: ${{ secrets.TOKEN }}  # 매우 중요
      
      - name: List files in the checked-out repository
        run: ls -l
      - name: Update Kubernetes resources
        run: |
          cd charts/myapp
          ls -al 
          # kustomize edit set image cicd-image=${{ secrets.DOCKERHUB_USERNAME }}/cicdlab_1:${{ github.event.workflow_run.head_commit.message }}
          sed -i 's/^\(\s*tag:\s*\).*/\1'${{ github.event.workflow_run.head_commit.message }}'/' values.yaml
          cat values.yaml

      - name: Set up Git user
        run: |
          git config --global user.name "integer-bin"
          git config --global user.email "integer-bin@github.com"

      - name: Add remote repository
        run: git remote add target_repo https://github.com/integer-bin/

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "${{ github.event.workflow_run.head_commit.message }}"
          # git commit -m "Automated commit"
          git push target_repo main